name: 'Blog Content Workflow'
description: 'Manages blog content through research and drafting stages using AI.'
author: 'Jules'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to commit changes back to the repo.'
    required: true
  PERPLEXITY_API_KEY:
    description: 'API key for Perplexity AI.'
    required: false # May not be needed if research is manual or if the action only handles draft stage
  CLAUDE_API_KEY:
    description: 'API key for Claude AI.'
    required: false # May not be needed if draft is manual or if the action only handles research stage
  GIT_USER_NAME:
    description: 'Git user name for commits.'
    required: false
    default: 'github-actions[bot]'
  GIT_USER_EMAIL:
    description: 'Git user email for commits.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  CONTENT_DIR:
    description: 'Directory where content files are stored (e.g., "posts").'
    required: false
    default: '.' # Defaults to repo root if not specified

runs:
  using: 'node20'
  main: 'dist/index.js' # We'll bundle our JS code into dist/index.js later

branding:
  icon: 'edit-3'
  color: 'blue'
