name: 'Research Workflow Action'
description: 'Processes blog post topics and generates research briefs using Perplexity AI'

inputs:
  notion-api-key:
    description: 'Notion API Key'
    required: true
  notion-blog-posts-id:
    description: 'Notion Blog Posts Database ID'
    required: true
  notion-drafts-id:
    description: 'Notion Drafts Database ID'
    required: true
  perplexity-api-key:
    description: 'Perplexity API Key'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
